import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Quick Hair",
  description: "Generated by Quick Hair",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient>
          <Toaster />
          <div className=" relative w-full min-h-screen ">
            <Navbar/>
            {children}
          </div>
        </QuaryClient>
      </body>
    </html>
  );
}
