import Navbar from "@/components/navbar";
import { authOptions } from "@/lib/auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Barber | Quick Hair",
  description: "Generated by Quick Hair",
};

export default async function BarberLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session =await getServerSession(authOptions)
  // const role = session?.user.role;
  // if (role !== "BARBER") {
  //   redirect('/');
  // }
  return (
    <main>
      <Navbar panel="barber" />
      {children}
    </main>
  );
}
